# Grab vanilla image
FROM tinkerpop/gremlin-server:3.7.0


ADD --chown=gremlin ./gremlin-server.yaml conf/gremlin-server.yaml
ADD --chown=gremlin ./tinkergraph-empty.properties conf/tinkergraph-empty.properties

